// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test_boost
void test_boost(int seed);
RcppExport SEXP parallelrng_test_boost(SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    test_boost(seed);
    return R_NilValue;
END_RCPP
}
