# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnorm_cpp <- function(seed = -1L, n = 1L) {
    .Call('parallelrng_rnorm_cpp', PACKAGE = 'parallelrng', seed, n)
}

