# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rnorm_boost <- function(n = 1L, seed = -1L) {
    .Call('parallelrng_rnorm_boost', PACKAGE = 'parallelrng', n, seed)
}

